### ISSUE TITLE
Already have munin-node / server built and running, just want the plugins.

### ISSUE THREAD

**Issue by dispo2** [saint-lascivious/munin-pihole-plugins#2]
So not really an issue just a request / question.

I already have munin up and running with munin-node on the pihole and munin (server) running on a separate machine.
The script installs munin server on the pihole but I just need the plugins but I'm not sure what other dependencies there are for the API access etc.

What do I need to install just for the plugins to work and is it possible to add that option to the install script ?

I can just run the installer and the graphs appear on my server without any extra work but I don't really want munin server running on my pihole or any other unecessary installed files.

Many thanks for the great work.

**Comment by dispo2** [comment]
Resolved.

Apologies I should have looked first. 

install_webserver="${INSTALL_WEBSERVER:-false}"

does this. I didnt equate webserver with munin server so thought this just skipped lighttpd

**Comment by saint-lascivious** [comment]
I'm going to leave this open for the moment at least. It's a valid issue, just in a larger area and scope than this case specifically.

It points to a larger hole in documentation / description / interface that should be plugged or otherwise investigated for better alternatives.

**Comment by saint-lascivious** [comment]
ee9a2d9 should provide the desired flexibility in a more readily accessible form, should no further issues in this line arise in the immediate future I will formally mark this as closed.

**Comment by dispo2** [comment]
fantastic, thank you.
